name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        timeout-minutes: 60
        run: npm run build

      - name: Check Changes
        id: diff
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.md
            **/*.xml

      - name: Push
        if: steps.diff.outputs.any_changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -am "chore: update `date`"
          git push origin main
